<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" dir="{{ app()->getLocale() === 'ar' ? 'rtl' : 'ltr' }}" class="h-full bg-[#FAF8F5]">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Two-Factor Verification - GOUNOW Management Platform</title>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@300;400;500;600;700&family=Playfair+Display:ital,wght@0,500;0,600;1,400&family=Tajawal:wght@400;500;700&display=swap" rel="stylesheet">

    <script src="https://cdn.tailwindcss.com"></script>
    <script>
        tailwind.config = {
            theme: {
                extend: {
                    colors: {
                        brand: {
                            terracotta: '#B85D3B',
                            'terracotta-dark': '#9A4A2B',
                            sand: '#E5DCD3',
                            'sand-light': '#F6F3EE',
                            'sand-card': '#FAF8F5',
                            brown: '#3D2E26',
                            'brown-muted': '#786B63',
                            border: '#E8E2D9',
                        }
                    },
                    fontFamily: {
                        sans: ['"Plus Jakarta Sans"', ...(navigator.language.startsWith('ar') ? ['Tajawal'] : []), 'sans-serif'],
                        serif: ['"Playfair Display"', 'serif'],
                        arabic: ['Tajawal', 'sans-serif'],
                    }
                }
            }
        }
    </script>
</head>
<body class="h-full flex flex-col justify-center py-12 sm:px-6 lg:px-8 bg-[#FAF8F5] text-brand-brown">

    <div class="sm:mx-auto sm:w-full sm:max-w-md text-center">
        <div class="inline-block p-1 bg-white rounded-2xl shadow-sm border border-brand-border mb-4">
            <img src="{{ asset('assets/images/logo.jpg') }}" alt="GOUNOW" class="h-16 w-16 rounded-xl object-cover">
        </div>
        <h2 class="text-2xl sm:text-3xl font-serif font-bold text-brand-brown tracking-tight">
            {{ app()->getLocale() === 'ar' ? 'التحقق بخطوتين' : 'Two-Factor Verification' }}
        </h2>
        <p class="mt-2 text-xs sm:text-sm text-brand-brown-muted max-w">
            {{ app()->getLocale() === 'ar' 
                ? 'أدخل رمز الأمان المكون من 6 أرقام من تطبيق المصادقة الخاص بك' 
                : 'Enter the 6-digit verification code generated by your authenticator app.' }}
        </p>
    </div>

    <div class="mt-8 sm:mx-auto sm:w-full sm:max-w-md px-4 sm:px-0">
        <div class="bg-white py-8 px-6 sm:px-10 shadow-xl rounded-3xl border border-brand-border" x-data="{ useRecovery: false }">
            
            @if ($errors->any())
                <div class="mb-6 p-4 rounded-2xl bg-rose-50 border border-rose-200 text-xs text-rose-700">
                    <ul class="list-disc list-inside space-y-1">
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <!-- TOTP Form -->
            <form id="totp-form" action="{{ route('admin.2fa.challenge') }}" method="POST" class="space-y-6">
                @csrf

                <div>
                    <label for="code" class="block text-xs font-bold uppercase tracking-wider text-brand-brown mb-2 text-center">
                        {{ app()->getLocale() === 'ar' ? 'رمز التحقق (6 أرقام)' : 'Security Code' }}
                    </label>
                    <div class="mt-1">
                        <input id="code" name="code" type="text" inputmode="numeric" pattern="[0-9]*" maxlength="6" autofocus required
                               placeholder="123456"
                               class="appearance-none block w-full px-4 py-3.5 text-center text-2xl tracking-[0.5em] font-mono border border-brand-border rounded-2xl placeholder-brand-brown-muted/40 focus:outline-none focus:ring-2 focus:ring-brand-terracotta focus:border-brand-terracotta transition-all bg-brand-sand-light/30">
                    </div>
                </div>

                <div>
                    <button type="submit"
                            class="w-full flex justify-center py-3.5 px-4 border border-transparent rounded-2xl shadow-sm text-xs font-bold uppercase tracking-wider text-white bg-brand-terracotta hover:bg-brand-terracotta-dark focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-brand-terracotta transition-all">
                        {{ app()->getLocale() === 'ar' ? 'تأكيد الرمز' : 'Verify & Continue' }}
                    </button>
                </div>
            </form>

            <div class="mt-6 pt-6 border-t border-brand-border text-center">
                <details class="text-xs text-brand-brown-muted">
                    <summary class="cursor-pointer font-semibold hover:text-brand-terracotta">
                        {{ app()->getLocale() === 'ar' ? 'استخدام رمز استرداد للطوارئ؟' : 'Lost your authenticator? Use a Recovery Code' }}
                    </summary>
                    <form action="{{ route('admin.2fa.recovery') }}" method="POST" class="mt-4 space-y-3 text-left">
                        @csrf
                        <label for="recovery_code" class="block text-[11px] font-bold uppercase tracking-wider text-brand-brown">
                            {{ app()->getLocale() === 'ar' ? 'رمز الاسترداد' : 'Emergency Recovery Code' }}
                        </label>
                        <input id="recovery_code" name="recovery_code" type="text" required placeholder="XXXX-XXXX"
                               class="appearance-none block w-full px-4 py-2.5 text-sm font-mono border border-brand-border rounded-xl placeholder-brand-brown-muted/40 focus:outline-none focus:ring-2 focus:ring-brand-terracotta bg-brand-sand-light/30">
                        <button type="submit"
                                class="w-full py-2.5 px-4 rounded-xl text-xs font-bold uppercase tracking-wider text-brand-terracotta border border-brand-terracotta hover:bg-brand-terracotta hover:text-white transition-all">
                            {{ app()->getLocale() === 'ar' ? 'استخدام رمز الاسترداد' : 'Consume Recovery Code' }}
                        </button>
                    </form>
                </details>
            </div>

            <div class="mt-6 text-center">
                <a href="{{ route('admin.login') }}" class="text-xs text-brand-brown-muted hover:text-brand-terracotta transition-colors">
                    &larr; {{ app()->getLocale() === 'ar' ? 'العودة لتسجيل الدخول' : 'Back to Login' }}
                </a>
            </div>

        </div>
    </div>
</body>
</html>
